name: Build and release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          sudo apt-get install zip -y
          cd src-gmod
          zip -r ../gwaa-gmod-addon.zip . -x 'README.md'
          cd ../src-nodejs
          zip -r ../gwaa-nodejs-app.zip . -x 'README.md' -x '.gitignore'

      - name: Release
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
        run: |
          gh release upload ${{github.event.release.tag_name}} gwaa-gmod-addon.zip gwaa-nodejs-app.zip
